### ISSUE TITLE
Db not found

### ISSUE THREAD

**Issue by brokenseal** [marianol/FreshDeliveryDemo#6]
Hello and thanks for this great example.
I am kinda stuck at this point

```
use that sql script to update your DB, at the command prompt: psql -U postgres -d foodmart -a -f FRESHDELIVERY_PATH/JasperServerResources/foodmart-store-update.sql Note: Use C:\ for Windows install.
```

I have a local postgresql installation but there's no foodmart db in there. Could it be that JasperSoft Server actually installs its own version of postgres, accessible but on a different port?

Thank in advance.

**Comment by danielpetzold** [comment]
Hi Davide,

Very soon there will be a more direct set of support on our community site
around these topics and the demo. In the meantime let me set you off in the
right direction. :)

The only thing that needs to be updated in this demo in terms of the
database (so far) is to add the lat/long to the foodmart db which is part
of the Jaspersoft bundle which includes Postgres. So this would be aside
from any Postgres database that you have that is existing. This is how we
include the demo data which you will see when using our product. You should
find this video here
https://www.youtube.com/watch?v=dGxV5xUgIfQ&list=PL5NudtWaQ9l6G1d06Z5qGmKWQYwUCO0xl#t=48
helpful as you work through our Postgres sample database. I believe the
default port is 5432 and username/password are both set to "postgres". I
personally like to use pgadmin for this type of work.

Finally you will find we are migrating over to a new location for these
sample on GitHub. You will find this repo here
https://github.com/TIBCOSoftware/JS-FDSample active within a week or so.

Thanks!
-Daniel

_Daniel Petzold_Product Manager

►
_415.348.2368 <415.348.2343> / 615-507-0866 <415.734.1949>
*►_dpetzold@tibco.com
fdelle@tibco.com*

**Comment by brokenseal** [comment]
Hello!
Thanks for the quick reply, that's awesome!

While investigating, I found out that my OSX installation of JasperSoft has indeed created a new postgresql installation, running on port 5433, as I thought.
Also, the username and password to connect to it were kind of a mystery to me, but I now found them inside the installation configuration inside its folder.

Long story short, this command worked for me:

```
psql --host=localhost --port=5433 --user=postgres -d foodmart -a -f foodmart-store-update.sql
```

I hope this helps.
Cheers.

**Comment by danielpetzold** [comment]
Great to hear Davide.

Also I highly recommend you check out the updated demo files here on GitHub
which will be live next Monday. https://github.com/TIBCOSoftware/JS-FDSample

This is where we will continue this demo, make updates and provide
connection to support in the future.

Best!
-Daniel

_Daniel Petzold_Product Manager

►
_415.348.2368 <415.348.2343> / 615-507-0866 <415.734.1949>
*►_dpetzold@tibco.com
fdelle@tibco.com*

**Comment by brokenseal** [comment]
I get a 404 error from that link :)

**Comment by danielpetzold** [comment]
Sorry. Should be up on 2/8/16.

_Daniel Petzold_Product Manager

►
_415.348.2368 <415.348.2343> / 615-507-0866 <415.734.1949>
*►_dpetzold@tibco.com
fdelle@tibco.com*

**Comment by brokenseal** [comment]
Ok, thanks again, I consider this issue solved :+1:
